### ISSUE TITLE
Changing python interpreter

### ISSUE THREAD

**Issue by thijstriemstra** [process1183/roomba-rpi#1] opened 2022-04-24 22:49 UTC
Thanks for creating https://github.com/process1183/roomba-rpi/blob/master/docs/ros2_rpizw_build.md, it helped a lot to get ros2 running on a raspberry pi 3b+.

Everything worked flawlessly, except this error:

```
$ ros2 run demo_nodes_cpp talker
-bash: /opt/ros2_foxy/install/bin/ros2: /usr/local/bin/python3.7: bad interpreter: No such file or directory
```

After adding a symlink in `/usr/local/bin/`:

```
sudo ln -s /usr/bin/python3.7 python3.7
```

The ros2 commands worked.

Now, my question, I compiled python 3.10 from source (and installed pyqt5 into a py3.10 virtual env) and I'd like to use Python 3.10 (`/usr/local/bin/python3.10`) for ROS2 as well. Would I have to recompile everything or is it a simple fix?

**Comment by process1183** [comment] 2022-04-28 07:10
I'm glad this was able to help you out! It's also worth noting that if you wanted to use Ubuntu 20.04 (arm64) on a RPi 3B+, you should be able to install ROS2 Foxy or Galactic using APT instead of needing to build from source.

For the Python 3.7 error, it looks like it's probably caused by a slightly different Python install between your build environment and RPi. What are you using for your build env (Docker container, VM, etc)?

To use Python 3.10, you would have to recompile ROS2, ensuring that cmake knows of your Python 3.10 install. Take a look at `/usr/share/cmake-3.13/Modules/FindPythonLibs.cmake`, which is what cmake uses to find Python installs. You will also probably need to change the `PYTHON_SOABI` value in `/opt/toolchain.cmake`.

**Comment by thijstriemstra** [comment] 2022-04-28 12:54
> if you wanted to use Ubuntu 20.04 (arm64) on a RPi 3B+, 

I'm trying to avoid ubuntu because I get the impression that it's too heavy for a Raspberry Pi 3b+, and more suitable for a Pi 4. Oh, and the number one reason: I'm using a HyperPixel 4.0 display with the Raspberry Pi, which doesn't work on Ubuntu.

> What are you using for your build env (Docker container, VM, etc)?

Regular Ubuntu 20.04 installation, no virtual stuff. Docker is too slow in general IMO.

> To use Python 3.10, you would have to recompile ROS2, ensuring that cmake knows of your Python 3.10 install. 

The header of `/usr/share/cmake-3.16/Modules/FindPythonLibs.cmake` (note it's using cmake-3.16, not 3.13 as you suggested) contains:

```
Use :module:`FindPython3`, :module:`FindPython2` or :module:`FindPython` instead.
```

Looks like `nano /usr/share/cmake-3.16/Modules/FindPython/Support.cmake` contains a Python 3.7 reference:

```
cmake_policy (VERSION 3.7)
```

I guess I'll have to change that to 3.10?

> You will also probably need to change the PYTHON_SOABI value in /opt/toolchain.cmake.

I changed this line in `/opt/toolchain.make`:

```
set(PYTHON_SOABI cpython-310m-arm-linux-gnueabihf)
```

Should I make these changes on the Raspberry Pi and rsync them to my machine or only change it in `/opt/rootfs` on my machine?

ps. would you accept a PR that replaces `RPiZW` with `RPi` in your document and mention it's tested on both devices?

**Comment by thijstriemstra** [comment] 2022-04-28 14:43
> Should I make these changes on the Raspberry Pi and rsync them to my machine or only change it in /opt/rootfs on my machine?

I made the changes only locally (eg cross compile machine) and am now compiling ROS2 again from scratch. Unfortunaly it failed this time (although I might have failed the first time as well, I never checked if rcl was working):

```
--- stderr: rcl                                                                                    
CMake Error at CMakeLists.txt:13 (find_package):
  By not providing "Findtracetools.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "tracetools", but CMake did not find one.

  Could not find a package configuration file provided by "tracetools" with
  any of the following names:

    tracetoolsConfig.cmake
    tracetools-config.cmake

  Add the installation prefix of "tracetools" to CMAKE_PREFIX_PATH or set
  "tracetools_DIR" to a directory containing one of the above files.  If
  "tracetools" provides a separate development package or SDK, be sure it has
  been installed.


---
Failed   <<< rcl [2.05s, exited with code 1]
Aborted  <<< geometry_msgs [1min 3s]                                            

Summary: 155 packages finished [8min 9s]
  1 package failed: rcl
  1 package aborted: geometry_msgs
  132 packages had stderr output: action_msgs action_tutorials_interfaces actionlib_msgs ament_cmake ament_cmake_auto ament_cmake_clang_format ament_cmake_clang_tidy ament_cmake_copyright ament_cmake_core ament_cmake_cppcheck ament_cmake_cpplint ament_cmake_export_definitions ament_cmake_export_dependencies ament_cmake_export_include_directories ament_cmake_export_interfaces ament_cmake_export_libraries ament_cmake_export_link_flags ament_cmake_export_targets ament_cmake_flake8 ament_cmake_gmock ament_cmake_google_benchmark ament_cmake_gtest ament_cmake_include_directories ament_cmake_libraries ament_cmake_lint_cmake ament_cmake_mypy ament_cmake_nose ament_cmake_pclint ament_cmake_pep257 ament_cmake_pycodestyle ament_cmake_pyflakes ament_cmake_pytest ament_cmake_python ament_cmake_ros ament_cmake_target_dependencies ament_cmake_test ament_cmake_uncrustify ament_cmake_version ament_cmake_xmllint ament_index_cpp ament_lint_auto ament_lint_common builtin_interfaces class_loader composition_interfaces connext_cmake_module console_bridge_vendor eigen3_cmake_module example_interfaces fastcdr fastrtps fastrtps_cmake_module foonathan_memory_vendor geometry_msgs gmock_vendor google_benchmark_vendor gtest_vendor kdl_parser launch_testing_ament_cmake libcurl_vendor libyaml_vendor lifecycle_msgs mimick_vendor orocos_kdl osrf_testing_tools_cpp pendulum_msgs performance_test_fixture pluginlib python_cmake_module rcl rcl_interfaces rcl_logging_log4cxx rcl_logging_noop rcl_logging_spdlog rcl_yaml_param_parser rcpputils rcutils resource_retriever rmw rmw_connext_cpp rmw_connext_shared_cpp rmw_cyclonedds_cpp rmw_dds_common rmw_fastrtps_cpp rmw_fastrtps_dynamic_cpp rmw_fastrtps_shared_cpp rmw_implementation rmw_implementation_cmake ros_environment rosgraph_msgs rosidl_adapter rosidl_cmake rosidl_default_generators rosidl_default_runtime rosidl_generator_c rosidl_generator_cpp rosidl_generator_dds_idl rosidl_generator_py rosidl_parser rosidl_runtime_c rosidl_runtime_cpp rosidl_typesupport_c rosidl_typesupport_connext_c rosidl_typesupport_connext_cpp rosidl_typesupport_cpp rosidl_typesupport_fastrtps_c rosidl_typesupport_fastrtps_cpp rosidl_typesupport_interface rosidl_typesupport_introspection_c rosidl_typesupport_introspection_cpp rttest shared_queues_vendor spdlog_vendor sqlite3_vendor statistics_msgs std_msgs std_srvs test_interface_files test_launch_testing test_msgs test_osrf_testing_tools_cpp test_rmw_implementation tinyxml2_vendor tinyxml_vendor tlsf uncrustify_vendor unique_identifier_msgs urdf urdfdom urdfdom_headers yaml_cpp_vendor zstd_vendor
  109 packages not processed
```

**Comment by thijstriemstra** [comment] 2022-04-28 15:38
> Unfortunaly it failed this time

For weird some reason `src/ros-tracing/ros2_tracing` wasn't checked out properly (dir was empty!) so after doing it manually:

```
cd ros2_foxy/src/ros-tracing/
rm -rf ros_tracing2
git clone https://gitlab.com/ros-tracing/ros2_tracing.git
cd ros2_tracing
git checkout foxy
cd ../../
```
and restarting the build it completed:

```
Summary: 272 packages finished [4min 59s]
```

Now I'll have to check if it uses Python3.10..

**Comment by thijstriemstra** [comment] 2022-04-28 15:47
> Now I'll have to check if it uses Python3.10..

Starting the talker went fine:

```
/opt/ros2_foxy $ ros2 run demo_nodes_cpp talker
[INFO] [1651160693.123779074] [talker]: Publishing: 'Hello World: 1'
[INFO] [1651160694.122663638] [talker]: Publishing: 'Hello World: 2'
[INFO] [1651160695.122489232] [talker]: Publishing: 'Hello World: 3'
[INFO] [1651160696.122382452] [talker]: Publishing: 'Hello World: 4'
[INFO] [1651160697.122268358] [talker]: Publishing: 'Hello World: 5'
[INFO] [1651160698.122066336] [talker]: Publishing: 'Hello World: 6'
[INFO] [1651160699.121911417] [talker]: Publishing: 'Hello World: 7'
[INFO] [1651160700.121799224] [talker]: Publishing: 'Hello World: 8'
```

But the listener throws this error:

```
$ ros2 run demo_nodes_py listener
Traceback (most recent call last):
  File "/opt/ros2_foxy/install/lib/demo_nodes_py/listener", line 33, in <module>
    sys.exit(load_entry_point('demo-nodes-py==0.9.3', 'console_scripts', 'listener')())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/ros2_foxy/install/lib/python3.7/site-packages/demo_nodes_py/topics/listener.py", line 16, in <module>
    from rclpy.node import Node
  File "/opt/ros2_foxy/install/lib/python3.7/site-packages/rclpy/node.py", line 41, in <module>
    from rclpy.client import Client
  File "/opt/ros2_foxy/install/lib/python3.7/site-packages/rclpy/client.py", line 22, in <module>
    from rclpy.impl.implementation_singleton import rclpy_implementation as _rclpy
  File "/opt/ros2_foxy/install/lib/python3.7/site-packages/rclpy/impl/implementation_singleton.py", line 31, in <module>
    rclpy_implementation = _import('._rclpy')
  File "/opt/ros2_foxy/install/lib/python3.7/site-packages/rclpy/impl/__init__.py", line 28, in _import
    return importlib.import_module(name, package='rclpy')
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'rclpy._rclpy'
The C extension '/opt/ros2_foxy/install/lib/python3.7/site-packages/rclpy/_rclpy.cpython-37m-arm-linux-gnueabihf.so' isn't present on the system. Please refer to 'https://index.ros.org/doc/ros2/Troubleshooting/Installation-Troubleshooting/#import-failing-without-library-present-on-the-system' for possible solutions
```

Only `/opt/ros2_foxy/install/lib/python3.7/site-packages/` exists, no `/opt/ros2_foxy/install/lib/python3.10/site-packages/`..

Looks like my rootfs doesn't contain the python3.10 libs in the regular location:

```
$ ls -l /opt/rootfs/lib/python
python2.7/ python3/   python3.7/
```

But libs are present in `/opt/rootfs/usr/local/lib`:

```
-rwxr-xr-x  1 root root  25340386 Apr  1 01:20 libpython3.10.a
drwxr-xr-x  2 root root      4096 Apr  1 01:23 pkgconfig
drwxr-xr-x  3 root root      4096 Jan 28 03:36 pypy2.7
drwxrwsr-x  4 root staff     4096 Jan 28 03:29 python2.7
drwxr-xr-x 36 root root      4096 Apr  1 01:21 python3.10
drwxrwsr-x  3 root staff     4096 Jan 28 03:28 python3.7
```

So I think I have to add these to the include paths (and put them first) like so:

```console
export C_INCLUDE_PATH="/opt/rootfs/usr/local/include:/opt/rootfs/usr/include:/opt/rootfs/usr/include/arm-linux-gnueabihf:/opt/rootfs/usr/lib/arm-linux-gnueabihf"
export CPLUS_INCLUDE_PATH="/opt/rootfs/usr/local/include:/opt/rootfs/usr/include:/opt/rootfs/usr/include/arm-linux-gnueabihf:/opt/rootfs/usr/lib/arm-linux-gnueabihf"
```

And recompile...

**Comment by thijstriemstra** [comment] 2022-04-28 17:40
Unfortunately that didn't make a difference, I'm giving up for now and sticking to stock Python 3.7.

**Comment by process1183** [comment] 2022-05-10 06:38
Sorry that this didn't end up working! I'm going to go ahead and close this issue for now.

**Closed as completed by process1183** 2022-05-10 06:38 UTC
Labels: question, wontfix
